### ISSUE TITLE
如何修改支持macos

### ISSUE THREAD

**Issue by laobei** [lisztomania-Zero/learning-power#1]

**Comment by laobei** [comment]
牛逼, 一用马上被检测到违规扣减1000分

**Comment by lisztomania-Zero** [comment]
没有没有，看下左上角，我只是全给展示出来

**Comment by lisztomania-Zero** [comment]
> 牛逼，一用马上被检测到违规扣减1000分

没有没有，看下左上角，我只是全给展示出来

**Comment by lisztomania-Zero** [comment]
> 牛逼，一用马上被检测到违规扣减1000分

还要继续打磨，我没有macOS，不过应该不用做修改就能用，没有太多的依赖

**Comment by laobei** [comment]
> > 牛逼，一用马上被检测到违规扣减1000分
> 
> 还要继续打磨，我没有macOS，不过应该不用做修改就能用，没有太多的依赖

调接口有没有把cookie信息带上, 时间随机挺好的, 6,7秒太短, 模拟手动点击吧

**Comment by lisztomania-Zero** [comment]
> > > 牛逼，一用马上被检测到违规扣减1000分
> > 
> > 
> > 还要继续打磨，我没有macOS，不过应该不用做修改就能用，没有太多的依赖
> 
> 调接口有没有把cookie信息带上, 时间随机挺好的, 6,7秒太短, 模拟手动点击吧

没有做持久化登录，6,7秒我还觉得有点长，主要是用来等待网页加载和模拟人工做题的速度。

**Comment by HowarWon** [comment]
macos 下专项答题10/10后报错了😂😂😂

**Comment by xin3721** [comment]
> macos 下专项答题10/10后报错了😂😂😂
我运行后显示了。。总是有TERM environment variable not set.而且用的m1的mac。。。浏览器是arm版，手动下载的驱动不认。。。。自动的下的也不对。。。。还是用回win下了。。。
