### ISSUE TITLE
专项答题的bug

### ISSUE THREAD

**Issue by justplus** [lisztomania-Zero/learning-power#12]
两个专项答题的bug，由于点太小，就不提PR了，请作者fix：

1. 已经得分的专项答题会重复答题，但是不会重复得分，所以需要将已得分的专题踢掉
analysis.py  __init_topic

            for topics in code['data_str']['list']:
                if not topics['overdue'] and topics['achievement']['correct'] != USER_PROJECT_ANSWER_TASKS:
                    self.__topic_list.append(topics)

2. 有种题型是选择型判断题，提示里面的信息不是标红的直接为答案，需要判断下是否一致，不一致才是错误
answer.py  __do_choosable

            t_answers = [correct['content'] for correct in answer['answers']]
            if len(t_answers) > 0:
                is_tstm = t_answers[0] == '正确'
                if is_tstm:
                    label = 'A' if descs[0] in self.__answer_topic_desc else 'B'
                    self.__answer_choosables[label].click()
                    time.sleep(0.1)
                else:
                    for correct in answer['answers']:
                        for desc in descs:
                            if correct['content'] == desc:
                                self.__answer_choosables[correct['label']].click()
                                time.sleep(0.1)

**Comment by zhoushiwang99** [comment]
![image](https://user-images.githubusercontent.com/43675156/104669951-f4ec7900-5715-11eb-8db5-f60438a5844c.png)
![image](https://user-images.githubusercontent.com/43675156/104669967-fae25a00-5715-11eb-96cd-b17af7789dc9.png)
这里有个变量没有声明

**Comment by zhoushiwang99** [comment]
![image](https://user-images.githubusercontent.com/43675156/104670053-1b121900-5716-11eb-9447-fc117e912837.png)
这里有个变量没有声明

**Comment by zhoushiwang99** [comment]
USER_PROJECT_ANSWER_TASKS变量没有声明
![image](https://user-images.githubusercontent.com/43675156/104670124-3aa94180-5716-11eb-936a-b94bb47f773d.png)

**Comment by zhoushiwang99** [comment]
应该是user_msg.USER_PROJECT_ANSWER_TASKS吧

**Comment by lisztomania-Zero** [comment]
现在换了答题方式，速度起飞
