### ISSUE TITLE
学习期间，发现问题并进行了一些改进（专项答题bug）

### ISSUE THREAD

**Issue by Swenchao** [lisztomania-Zero/learning-power#16]
1. mac系统在自动安装chromedriver后，可能会遇到权限不足情况

[init_driver.py]

添加权限操作（只添加这一句）

os.chmod(DRIVER_FILE, 755)

driver = webdriver.Chrome(
    desired_capabilities=caps,
    executable_path=DRIVER_FILE,
)

2. 专项答题匹配不上，没法进行选项选择和下一题

[answer.py]

做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)

(1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):

(2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):

3. 专项答题由于一些标点符号问题，选项不全。

[answer.py]

做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)

(1) if correct['content'] == desc:

(2) if correct['content'].replace("“", "").replace("”", "") == desc:

以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR

**Comment by Fantasy2Me** [comment]
> 1. mac系统在自动安装chromedriver后，可能会遇到权限不足情况
> 
> [init_driver.py]
> 
> 添加权限操作（只添加这一句）
> 
> os.chmod(DRIVER_FILE, 755)
> 
> driver = webdriver.Chrome(
> desired_capabilities=caps,
> executable_path=DRIVER_FILE,
> )
> 
> 1. 专项答题匹配不上，没法进行选项选择和下一题
> 
> [answer.py]
> 
> 做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)
> 
> (1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):
> 
> (2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):
> 
> 1. 专项答题由于一些标点符号问题，选项不全。
> 
> [answer.py]
> 
> 做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)
> 
> (1) if correct['content'] == desc:
> 
> (2) if correct['content'].replace("“", "").replace("”", "") == desc:
> 
> 以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR

谢谢大佬，完美解决

**Comment by doveshelly** [comment]
用这个会被查出来封号吗

**Comment by Swenchao** [comment]
> 用这个会被查出来封号吗

原则应该不会吧，因为整个过程就是模仿的你浏览器操作。   个人理解😂

**Comment by Fantasy2Me** [comment]
> > 用这个会被查出来封号吗
> 
> 原则应该不会吧，因为整个过程就是模仿的你浏览器操作。 个人理解😂
> 
> 在大佬代码基础上，自己又做了一些修改，有需要的可以联系我～
老哥，发我份呗，846394330@qq.com，谢谢~

**Comment by Swenchao** [comment]
> > > 用这个会被查出来封号吗
> > 
> > 
> > 原则应该不会吧，因为整个过程就是模仿的你浏览器操作。 个人理解😂
> > 在大佬代码基础上，自己又做了一些修改，有需要的可以联系我～
> > 老哥，发我份呗，[846394330@qq.com](mailto:846394330@qq.com)，谢谢~

好的，这两天没在那个电脑旁，等方便给你发哈~

**Comment by hebeghost** [comment]
> 1. mac系统在自动安装chromedriver后，可能会遇到权限不足情况
> 
> [init_driver.py]
> 
> 添加权限操作（只添加这一句）
> 
> os.chmod(DRIVER_FILE, 755)
> 
> driver = webdriver.Chrome(
> desired_capabilities=caps,
> executable_path=DRIVER_FILE,
> )
> 
> 1. 专项答题匹配不上，没法进行选项选择和下一题
> 
> [answer.py]
> 
> 做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)
> 
> (1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):
> 
> (2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):
> 
> 1. 专项答题由于一些标点符号问题，选项不全。
> 
> [answer.py]
> 
> 做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)
> 
> (1) if correct['content'] == desc:
> 
> (2) if correct['content'].replace("“", "").replace("”", "") == desc:
> 
> 以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR

您好能发给我一份吗，感激万分~ 89327rpg@163.com

**Comment by Swenchao** [comment]
> > > > 用这个会被查出来封号吗
> > > 
> > > 
> > > 原则应该不会吧，因为整个过程就是模仿的你浏览器操作。 个人理解😂
> > > 在大佬代码基础上，自己又做了一些修改，有需要的可以联系我～
> > > 老哥，发我份呗，[846394330@qq.com](mailto:846394330@qq.com)，谢谢~
> 
> 好的，这两天没在那个电脑旁，等方便给你发哈~

老哥，已经发了，注意查收~

**Comment by Swenchao** [comment]
> > 1. mac系统在自动安装chromedriver后，可能会遇到权限不足情况
> > 
> > [init_driver.py]
> > 添加权限操作（只添加这一句）
> > os.chmod(DRIVER_FILE, 755)
> > driver = webdriver.Chrome(
> > desired_capabilities=caps,
> > executable_path=DRIVER_FILE,
> > )
> > 
> > 1. 专项答题匹配不上，没法进行选项选择和下一题
> > 
> > [answer.py]
> > 做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)
> > (1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):
> > (2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):
> > 
> > 1. 专项答题由于一些标点符号问题，选项不全。
> > 
> > [answer.py]
> > 做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)
> > (1) if correct['content'] == desc:
> > (2) if correct['content'].replace("“", "").replace("”", "") == desc:
> > 以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR
> 
> 您好能发给我一份吗，感激万分~ [89327rpg@163.com](mailto:89327rpg@163.com)

老哥，已经发了，注意查收~

**Comment by hebeghost** [comment]
> > > 1. mac系统在自动安装chromedriver后，可能会遇到权限不足情况
> > > 
> > > [init_driver.py]
> > > 添加权限操作（只添加这一句）
> > > os.chmod(DRIVER_FILE, 755)
> > > driver = webdriver.Chrome(
> > > desired_capabilities=caps,
> > > executable_path=DRIVER_FILE,
> > > )
> > > 
> > > 1. 专项答题匹配不上，没法进行选项选择和下一题
> > > 
> > > [answer.py]
> > > 做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)
> > > (1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):
> > > (2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):
> > > 
> > > 1. 专项答题由于一些标点符号问题，选项不全。
> > > 
> > > [answer.py]
> > > 做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)
> > > (1) if correct['content'] == desc:
> > > (2) if correct['content'].replace("“", "").replace("”", "") == desc:
> > > 以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR
> > 
> > 
> > 您好能发给我一份吗，感激万分~ [89327rpg@163.com](mailto:89327rpg@163.com)
> 
> 老哥，已经发了，注意查收~

非常感谢，谢谢您

**Comment by xhztwyf** [comment]
> > 用这个会被查出来封号吗
> 
> 原则应该不会吧，因为整个过程就是模仿的你浏览器操作。 个人理解😂
> 
> 在大佬代码基础上，自己又做了一些修改，有需要的可以联系我～
您好，也能发我一份吗，谢谢    274388092@qq.com

**Comment by xin3721** [comment]
> 1. mac系统在自动安装chromedriver后，可能会遇到权限不足情况
> 
> [init_driver.py]
> 
> 添加权限操作（只添加这一句）
> 
> os.chmod(DRIVER_FILE, 755)
> 
> driver = webdriver.Chrome(
> desired_capabilities=caps,
> executable_path=DRIVER_FILE,
> )
> 
> 1. 专项答题匹配不上，没法进行选项选择和下一题
> 
> [answer.py]
> 
> 做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)
> 
> (1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):
> 
> (2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):
> 
> 1. 专项答题由于一些标点符号问题，选项不全。
> 
> [answer.py]
> 
> 做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)
> 
> (1) if correct['content'] == desc:
> 
> (2) if correct['content'].replace("“", "").replace("”", "") == desc:
> 
> 以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR

老哥，想咨询一下，驱动都问题，有没有遇到驱动里和现在用chrome版本没有匹配都，怎么办？谢谢！

**Comment by xhztwyf** [comment]
大佬，我对编程不懂的，真帮不上你忙。非常感谢您的帮助！谢谢！谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xin3721"<notifications@github.com&gt;; 
发送时间: 2021年1月27日(星期三) 凌晨1:35
收件人: "lisztomania-Zero/learning-power"<learning-power@noreply.github.com&gt;; 
抄送: "隨風而逝"<274388092@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lisztomania-Zero/learning-power] 学习期间，发现问题并进行了一些改进（专项答题bug） (#16)





   
mac系统在自动安装chromedriver后，可能会遇到权限不足情况
  
[init_driver.py]
 
添加权限操作（只添加这一句）
 
os.chmod(DRIVER_FILE, 755)
 
driver = webdriver.Chrome(
 desired_capabilities=caps,
 executable_path=DRIVER_FILE,
 )
  
专项答题匹配不上，没法进行选项选择和下一题
  
[answer.py]
 
做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)
 
(1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):
 
(2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):
  
专项答题由于一些标点符号问题，选项不全。
  
[answer.py]
 
做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)
 
(1) if correct['content'] == desc:
 
(2) if correct['content'].replace("“", "").replace("”", "") == desc:
 
以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR
  
老哥，想咨询一下，驱动都问题，有没有遇到驱动里和现在用chrome版本没有匹配都，怎么办？谢谢！

**Comment by Swenchao** [comment]
> > > 用这个会被查出来封号吗
> > 
> > 
> > 原则应该不会吧，因为整个过程就是模仿的你浏览器操作。 个人理解😂
> > 在大佬代码基础上，自己又做了一些修改，有需要的可以联系我～
> > 您好，也能发我一份吗，谢谢    [274388092@qq.com](mailto:274388092@qq.com)

已发送，注意查收~

**Comment by Swenchao** [comment]
> > 1. mac系统在自动安装chromedriver后，可能会遇到权限不足情况
> > 
> > [init_driver.py]
> > 添加权限操作（只添加这一句）
> > os.chmod(DRIVER_FILE, 755)
> > driver = webdriver.Chrome(
> > desired_capabilities=caps,
> > executable_path=DRIVER_FILE,
> > )
> > 
> > 1. 专项答题匹配不上，没法进行选项选择和下一题
> > 
> > [answer.py]
> > 做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)
> > (1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):
> > (2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):
> > 
> > 1. 专项答题由于一些标点符号问题，选项不全。
> > 
> > [answer.py]
> > 做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)
> > (1) if correct['content'] == desc:
> > (2) if correct['content'].replace("“", "").replace("”", "") == desc:
> > 以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR
> 
> 老哥，想咨询一下，驱动都问题，有没有遇到驱动里和现在用chrome版本没有匹配都，怎么办？目前状况是m1都机器，用的arm版chrome。。。。去下载intel版？谢谢！

我用m1可以啊。这个有可能是跟chrome小版本有关，不知道你的是不是这个问题。chrome新更新小版本后，可能就找不到对应的驱动。比如，前段时间这个版本87.0.4280.141就找不到对应的版本号，你只需要找个能对上大版本（就是前面的87）的就行。

**Comment by lisztomania-Zero** [comment]
换了答题方式，现在应该没问题了

**Comment by lisztomania-Zero** [comment]
> > > 1. mac系统在自动安装chromedriver后，可能会遇到权限不足情况
> > > 
> > > [init_driver.py]
> > > 添加权限操作（只添加这一句）
> > > os.chmod(DRIVER_FILE, 755)
> > > driver = webdriver.Chrome(
> > > desired_capabilities=caps,
> > > executable_path=DRIVER_FILE,
> > > )
> > > 
> > > 1. 专项答题匹配不上，没法进行选项选择和下一题
> > > 
> > > [answer.py]
> > > 做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)
> > > (1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):
> > > (2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):
> > > 
> > > 1. 专项答题由于一些标点符号问题，选项不全。
> > > 
> > > [answer.py]
> > > 做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)
> > > (1) if correct['content'] == desc:
> > > (2) if correct['content'].replace("“", "").replace("”", "") == desc:
> > > 以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR
> > 
> > 
> > 老哥，想咨询一下，驱动都问题，有没有遇到驱动里和现在用chrome版本没有匹配都，怎么办？目前状况是m1都机器，用的arm版chrome。。。。去下载intel版？谢谢！
> 
> 我用m1可以啊。这个有可能是跟chrome小版本有关，不知道你的是不是这个问题。chrome新更新小版本后，可能就找不到对应的驱动。比如，前段时间这个版本87.0.4280.141就找不到对应的版本号，你只需要找个能对上大版本（就是前面的87）的就行。

现在自动检测Chrome版本，然后自动匹配下载驱动了，之前做的是版本全匹配，后来发现只要匹配版本号前三个就行了

**Comment by xin3721** [comment]
> > > 1. mac系统在自动安装chromedriver后，可能会遇到权限不足情况
> > > 
> > > [init_driver.py]
> > > 添加权限操作（只添加这一句）
> > > os.chmod(DRIVER_FILE, 755)
> > > driver = webdriver.Chrome(
> > > desired_capabilities=caps,
> > > executable_path=DRIVER_FILE,
> > > )
> > > 
> > > 1. 专项答题匹配不上，没法进行选项选择和下一题
> > > 
> > > [answer.py]
> > > 做如下修改（文本不匹配，进行修改匹配）：将 (1) 修改成 (2)
> > > (1) if self.__answer_topic_desc in answer['body'].replace('（）', ''):
> > > (2) if self.__answer_topic_desc.replace('\n', '') in answer['body'].replace('（）', '').replace('--|--', '来源：'):
> > > 
> > > 1. 专项答题由于一些标点符号问题，选项不全。
> > > 
> > > [answer.py]
> > > 做如下修改（对标点符号进行替换）：将 (1) 修改成 (2)
> > > (1) if correct['content'] == desc:
> > > (2) if correct['content'].replace("“", "").replace("”", "") == desc:
> > > 以上修改在mac系统都是可行的，其他不敢保证。大佬有需要我可以直接提PR
> > 
> > 
> > 老哥，想咨询一下，驱动都问题，有没有遇到驱动里和现在用chrome版本没有匹配都，怎么办？目前状况是m1都机器，用的arm版chrome。。。。去下载intel版？谢谢！
> 
> 我用m1可以啊。这个有可能是跟chrome小版本有关，不知道你的是不是这个问题。chrome新更新小版本后，可能就找不到对应的驱动。比如，前段时间这个版本87.0.4280.141就找不到对应的版本号，你只需要找个能对上大版本（就是前面的87）的就行。嗯嗯，应该是小版本的问题。。谢谢~
