### ISSUE TITLE
mac系统检测到谷歌浏览器未安装，无法进行本程序

### ISSUE THREAD

**Issue by zijun-he** [lisztomania-Zero/learning-power#19]
iMac:learning-power-master $ python main.py 
/bin/sh: google-chrome: command not found
检测到谷歌浏览器未安装，无法进行本程序

**Comment by lisztomania-Zero** [comment]
我没有Mac，Mac命令行查询谷歌浏览器版本命令以及返回值是啥？？我以为跟Linux一样

**Comment by zijun-he** [comment]
iMac:~ $ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 88.0.4324.96

**Comment by lisztomania-Zero** [comment]
> iMac:~ $ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
> Google Chrome 88.0.4324.96

我改了，你试试看

**Comment by zijun-he** [comment]
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    MITMDUMP().Open()
  File "/Users/zrz/Desktop/learning-power-master/inside/Task/Mitmdump/Mitmdump.py", line 36, in Open
    self.__mitmdump = subprocess.Popen('mitmdump -q -p 8080 -s '+PATH().Intercept)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mitmdump -q -p 8080 -s /Users/zrz/Desktop/learning-power-master/inside/Task\\Mitmdump\\Intercept.py'

**Comment by lisztomania-Zero** [comment]
> Traceback (most recent call last):
> File "main.py", line 24, in
> MITMDUMP().Open()
> File "/Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Mitmdump.py", line 36, in Open
> self.__mitmdump = subprocess.Popen('mitmdump -q -p 8080 -s '+PATH().Intercept)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task\Mitmdump\Intercept.py'

MacOS咋用mitmdump？我也不晓得命令是啥？？23333

**Comment by lisztomania-Zero** [comment]
> > Traceback (most recent call last):
> > File "main.py", line 24, in
> > MITMDUMP().Open()
> > File "/Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Mitmdump.py", line 36, in Open
> > self.__mitmdump = subprocess.Popen('mitmdump -q -p 8080 -s '+PATH().Intercept)
> > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in **init**
> > self._execute_child(args, executable, preexec_fn, close_fds,
> > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
> > raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: 'mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task\Mitmdump\Intercept.py'
> 
> MacOS咋用mitmdump？我也不晓得命令是啥？？23333

这个是mitmdump执行错误导致的

**Comment by lisztomania-Zero** [comment]
> > > Traceback (most recent call last):
> > > File "main.py", line 24, in
> > > MITMDUMP().Open()
> > > File "/Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Mitmdump.py", line 36, in Open
> > > self.__mitmdump = subprocess.Popen('mitmdump -q -p 8080 -s '+PATH().Intercept)
> > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in **init**
> > > self._execute_child(args, executable, preexec_fn, close_fds,
> > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
> > > raise child_exception_type(errno_num, err_msg, err_filename)
> > > FileNotFoundError: [Errno 2] No such file or directory: 'mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task\Mitmdump\Intercept.py'
> > 
> > 
> > MacOS咋用mitmdump？我也不晓得命令是啥？？23333
> 
> 这个是mitmdump执行错误导致的

你直接执行这个试试：mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task\Mitmdump\Intercept.py

**Comment by lisztomania-Zero** [comment]
> > > > Traceback (most recent call last):
> > > > File "main.py", line 24, in
> > > > MITMDUMP().Open()
> > > > File "/Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Mitmdump.py", line 36, in Open
> > > > self.__mitmdump = subprocess.Popen('mitmdump -q -p 8080 -s '+PATH().Intercept)
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in **init**
> > > > self._execute_child(args, executable, preexec_fn, close_fds,
> > > > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
> > > > raise child_exception_type(errno_num, err_msg, err_filename)
> > > > FileNotFoundError: [Errno 2] No such file or directory: 'mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task\Mitmdump\Intercept.py'
> > > 
> > > 
> > > MacOS咋用mitmdump？我也不晓得命令是啥？？23333
> > 
> > 
> > 这个是mitmdump执行错误导致的
> 
> 你直接执行这个试试：mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task\Mitmdump\Intercept.py

可能是找不到Intercept.py这个文件

**Comment by zijun-he** [comment]
在终端使用mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py 
如下结果
mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py 
Loading script /Users/zrz/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
Proxy server listening at http://*:8080
mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py 
长时间无返回结果

**Comment by lisztomania-Zero** [comment]
> 在终端使用mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> 如下结果
> mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> Loading script /Users/zrz/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> Proxy server listening at http://*:8080
> mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> 长时间无返回结果

没反应就对了

**Comment by lisztomania-Zero** [comment]
> > 在终端使用mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > 如下结果
> > mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > Loading script /Users/zrz/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > Proxy server listening at http://*:8080
> > mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > 长时间无返回结果
> 
> 没反应就对了

程序报错应该是转义符的原因

**Comment by lisztomania-Zero** [comment]
> > > 在终端使用mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > > 如下结果
> > > mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > > Loading script /Users/zrz/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > > Proxy server listening at http://*:8080
> > > mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > > 长时间无返回结果
> > 
> > 
> > 没反应就对了
> 
> 程序报错应该是转义符的原因



> > > 在终端使用mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > > 如下结果
> > > mitmdump -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > > Loading script /Users/zrz/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > > Proxy server listening at http://*:8080
> > > mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py
> > > 长时间无返回结果
> > 
> > 
> > 没反应就对了
> 
> 程序报错应该是转义符的原因

我改了，你再试试

**Comment by zijun-he** [comment]
是否静音(Y/n):y
是否显示自动化过程(y/N):y
是否持久化登录(Y/n):y
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    MITMDUMP().Open()
  File "/Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Mitmdump.py", line 36, in Open
    self.__mitmdump = subprocess.Popen('mitmdump -q -p 8080 -s '+PATH().Intercept)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py'
zrzbook:learning-power-master zrz$

**Comment by lisztomania-Zero** [comment]
> 是否静音(Y/n):y
> 是否显示自动化过程(y/N):y
> 是否持久化登录(Y/n):y
> Traceback (most recent call last):
> File "main.py", line 24, in
> MITMDUMP().Open()
> File "/Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Mitmdump.py", line 36, in Open
> self.__mitmdump = subprocess.Popen('mitmdump -q -p 8080 -s '+PATH().Intercept)
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py'

我弄个MacOs试试

**Comment by lisztomania-Zero** [comment]
> > 是否静音(Y/n):y
> > 是否显示自动化过程(y/N):y
> > 是否持久化登录(Y/n):y
> > Traceback (most recent call last):
> > File "main.py", line 24, in
> > MITMDUMP().Open()
> > File "/Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Mitmdump.py", line 36, in Open
> > self.__mitmdump = subprocess.Popen('mitmdump -q -p 8080 -s '+PATH().Intercept)
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in **init**
> > self._execute_child(args, executable, preexec_fn, close_fds,
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
> > raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: 'mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py'
> 
> 我弄个MacOs试试

找到原因了，在mac里面/Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py这样读取不到Intercept.py，你可以用Tap一步一步补全试试，要加上~/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py才能读到

**Comment by lisztomania-Zero** [comment]
> 是否静音(Y/n):y
> 是否显示自动化过程(y/N):y
> 是否持久化登录(Y/n):y
> Traceback (most recent call last):
> File "main.py", line 24, in
> MITMDUMP().Open()
> File "/Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Mitmdump.py", line 36, in Open
> self.__mitmdump = subprocess.Popen('mitmdump -q -p 8080 -s '+PATH().Intercept)
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'mitmdump -q -p 8080 -s /Users/wq/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept.py'

![image](https://user-images.githubusercontent.com/50130180/106158520-ca42fb80-61be-11eb-9bd9-ebcc4e1fd0fb.png)
没问题了，修复了

**Comment by zijun-he** [comment]
顺利运行感谢~
