### ISSUE TITLE
正常运行到一半报错

### ISSUE THREAD

**Issue by nqianaaron** [lisztomania-Zero/learning-power#20]
选择的是全部都做1 2 3 4 5，大概做到30分的时候，提示
要选读文章:6.0分      视听学习:6.0分  专项答题:0分    每周答题:0分    每日答题:5.0分
分享:0分        收藏:0分        登录:1.0分      我要选读文章-时长:6.0分 订阅:0分
视听学习时长:6.0分      发表观点:0分    连续学习达标:0分        挑战答题:0分    参加调查问卷活动:0分
本地频道:0分    强国运动:0分    积分补发:0分    争上游答题:0分  【积分优化】一次性调整:0分
违规扣减:0分    双人对战:0分    问卷调查活动:0分
Traceback (most recent call last):
  File "C:\Users\hellsion\Desktop\learning-power-master\main.py", line 33, in <module>
    task.Task()
  File "C:\Users\hellsion\Desktop\learning-power-master\inside\Task\Task_Manage.py", line 206, in Task
    self.__Check_Weekly_Answer()
  File "C:\Users\hellsion\Desktop\learning-power-master\inside\Task\Task_Manage.py", line 164, in __Check_Weekly_Answer
    temp.Do(link=API().Weekly_Answer_Topic.geturl().format(num=iid))
  File "C:\Users\hellsion\Desktop\learning-power-master\inside\Task\Task_Answer.py", line 168, in Do
    seq = int(self.Topic_Seq().split('/')[-1])
ValueError: invalid literal for int() with base 10: ''

不知道是什么问题。是不是因为每周答题或者专项答题没有了？哎。在吐槽一下，以前留的每周答题，还有专项答题全部过期了。这个改版真的是醉了。

**Comment by zhoushiwang99** [comment]
我也遇到了

**Comment by lisztomania-Zero** [comment]
呃，如果每周答题和专项答题没有了，就会这样

**Comment by lisztomania-Zero** [comment]
> 选择的是全部都做1 2 3 4 5，大概做到30分的时候，提示
> 要选读文章:6.0分 视听学习:6.0分 专项答题:0分 每周答题:0分 每日答题:5.0分
> 分享:0分 收藏:0分 登录:1.0分 我要选读文章-时长:6.0分 订阅:0分
> 视听学习时长:6.0分 发表观点:0分 连续学习达标:0分 挑战答题:0分 参加调查问卷活动:0分
> 本地频道:0分 强国运动:0分 积分补发:0分 争上游答题:0分 【积分优化】一次性调整:0分
> 违规扣减:0分 双人对战:0分 问卷调查活动:0分
> Traceback (most recent call last):
> File "C:\Users\hellsion\Desktop\learning-power-master\main.py", line 33, in
> task.Task()
> File "C:\Users\hellsion\Desktop\learning-power-master\inside\Task\Task_Manage.py", line 206, in Task
> self.__Check_Weekly_Answer()
> File "C:\Users\hellsion\Desktop\learning-power-master\inside\Task\Task_Manage.py", line 164, in __Check_Weekly_Answer
> temp.Do(link=API().Weekly_Answer_Topic.geturl().format(num=iid))
> File "C:\Users\hellsion\Desktop\learning-power-master\inside\Task\Task_Answer.py", line 168, in Do
> seq = int(self.Topic_Seq().split('/')[-1])
> ValueError: invalid literal for int() with base 10: ''
> 
> 不知道是什么问题。是不是因为每周答题或者专项答题没有了？哎。在吐槽一下，以前留的每周答题，还有专项答题全部过期了。这个改版真的是醉了。

现在答题的速度明显变快了啊
