### ISSUE TITLE
运行有时候会卡住，专项答题正确率不高

### ISSUE THREAD

**Issue by zhoushiwang99** [lisztomania-Zero/learning-power#21]
RT

**Comment by lisztomania-Zero** [comment]
具体在哪个选项卡住呢？提供一下专项答题的名称，因为专项答题是要进行识别答案，可能会有点不准

**Comment by zhoushiwang99** [comment]
![image](https://user-images.githubusercontent.com/43675156/106251489-ff4b5e80-624f-11eb-8bcb-b018e66534fc.png)
这两个答题都有错误。卡住的话，刷视频和文章的时候有时候会卡住。

**Comment by lisztomania-Zero** [comment]
是进度条卡住吗？如果不是的话，那就是在获取文章或视频任务的链接时，会等的时间久一点

**Comment by zhoushiwang99** [comment]
不是进度条卡住，我明天截个图看看吧，今天的话已经刷完了

**Comment by lisztomania-Zero** [comment]
应该是获取任务链接的时候卡的，没有报错吧？

**Comment by lisztomania-Zero** [comment]
专项答题的话，应该是答案匹配的时候出了问题

**Comment by zhoushiwang99** [comment]
emmm，那个卡住的具体情况我也记不太清了，明天再来，哈哈哈

**Comment by lisztomania-Zero** [comment]
行，有什么问题，或有什么好的想法，issue，我会及时回复的。
