### ISSUE TITLE
软件未安装问题

### ISSUE THREAD

**Issue by xingkongwl** [lisztomania-Zero/learning-power#24]
PS D:\软件安装包\learning-power-master\learning-power-master> python main.py
检测到谷歌浏览器未安装，无法进行本程序

都安装完了，还是提示这个，谷歌浏览器是必须卸载再重新安一边你的那个同版本吗，db.db这个文件夹也没生成

Starting ChromeDriver 88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

安装的那个谷歌浏览器exe文件打开就是这样的提示，也是正常安装了啊
很懵，求大佬解答，看一下您的 邮箱呗

**Comment by lisztomania-Zero** [comment]
![image](https://user-images.githubusercontent.com/50130180/106369543-71758d80-638d-11eb-921c-f376eeee6a1a.png)
windows是通过查询注册表来获取Chrome版本的，你装的是正版的Chrome？或者你注册表中Chrome版本的位置是？？

**Comment by nqianaaron** [comment]
好奇怪,为什么我的谷歌浏览器版本是版本 88.0.4324.104（正式版本） （64 位）  没有96.然后驱动一直不对..我应该安装的就是正版的chrome啊

**Comment by 506430136** [comment]
https://npm.taobao.org/mirrors/chromedriver/88.0.4324.96/ 
你去这里手动下载一个chromedriver_win32.zip ，解压后拷贝到\learning-power-master\Driver\，应该就可以了

**Comment by xingkongwl** [comment]
> https://npm.taobao.org/mirrors/chromedriver/88.0.4324.96/
> 你去这里手动下载一个chromedriver_win32.zip，解压后拷贝到\ learning-power-master \ Driver \，应该就可以了


我的就是正版谷歌浏览器，你那win32的也放在learning-power-master \ Driver里面了，运行py还是提示检测到谷歌浏览器未安装，无法进行本程序，有解吗

**Comment by lisztomania-Zero** [comment]
> > https://npm.taobao.org/mirrors/chromedriver/88.0.4324.96/
> > 你去这里手动下载一个chromedriver_win32.zip，解压后拷贝到\ learning-power-master \ Driver \，应该就可以了
> 
> 我的就是正版谷歌浏览器，你那win32的也放在learning-power-master \ Driver里面了，运行py还是提示检测到谷歌浏览器未安装，无法进行本程序，有解吗

你看下我上面的回复，在你的注册表找找，看对应路径下是否是一样的信息

**Comment by lisztomania-Zero** [comment]
> > > https://npm.taobao.org/mirrors/chromedriver/88.0.4324.96/
> > > 你去这里手动下载一个chromedriver_win32.zip，解压后拷贝到\ learning-power-master \ Driver \，应该就可以了
> > 
> > 
> > 我的就是正版谷歌浏览器，你那win32的也放在learning-power-master \ Driver里面了，运行py还是提示检测到谷歌浏览器未安装，无法进行本程序，有解吗
> 
> 你看下我上面的回复，在你的注册表找找，看对应路径下是否是一样的信息

如果没有，那你找找你的Chrome版本信息在哪个路径下面

**Comment by lisztomania-Zero** [comment]
> > > > https://npm.taobao.org/mirrors/chromedriver/88.0.4324.96/
> > > > 你去这里手动下载一个chromedriver_win32.zip，解压后拷贝到\ learning-power-master \ Driver \，应该就可以了
> > > 
> > > 
> > > 我的就是正版谷歌浏览器，你那win32的也放在learning-power-master \ Driver里面了，运行py还是提示检测到谷歌浏览器未安装，无法进行本程序，有解吗
> > 
> > 
> > 你看下我上面的回复，在你的注册表找找，看对应路径下是否是一样的信息
> 
> 如果没有，那你找找你的Chrome版本信息在哪个路径下面

或者你在cmd中执行一下：wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version 试试看看能不能获取到版本号

**Comment by lisztomania-Zero** [comment]
> > > > > https://npm.taobao.org/mirrors/chromedriver/88.0.4324.96/
> > > > > 你去这里手动下载一个chromedriver_win32.zip，解压后拷贝到\ learning-power-master \ Driver \，应该就可以了
> > > > 
> > > > 
> > > > 我的就是正版谷歌浏览器，你那win32的也放在learning-power-master \ Driver里面了，运行py还是提示检测到谷歌浏览器未安装，无法进行本程序，有解吗
> > > 
> > > 
> > > 你看下我上面的回复，在你的注册表找找，看对应路径下是否是一样的信息
> > 
> > 
> > 如果没有，那你找找你的Chrome版本信息在哪个路径下面
> 
> 或者你在cmd中执行一下：wmic datafile where name="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" get Version 试试看看能不能获取到版本号

因为windows下获取Chrome版本号，目前最有效的方法还是查注册表。

**Comment by nqianaaron** [comment]
好奇怪，我的浏览器上面查询到的是版本 88.0.4324.104（正式版本） （64 位）。然后我去查找了一下注册表。居然是这个73.0.3683.86，难怪即使我自动下载了驱动也没有用。

**Comment by lisztomania-Zero** [comment]
> 好奇怪，我的浏览器上面查询到的是版本 88.0.4324.104（正式版本） （64 位）。然后我去查找了一下注册表。居然是这个73.0.3683.86，难怪即使我自动下载了驱动也没有用。

那就对了，是你系统问题了，不应该啊，还能这样的，淦

**Comment by lisztomania-Zero** [comment]
> > 好奇怪，我的浏览器上面查询到的是版本 88.0.4324.104（正式版本） （64 位）。然后我去查找了一下注册表。居然是这个73.0.3683.86，难怪即使我自动下载了驱动也没有用。
> 
> 那就对了，是你系统问题了，不应该啊，还能这样的，淦

自动下载的驱动你跟你注册表中版本一致的，你实际又不是

**Comment by nqianaaron** [comment]
所以啊。特别的奇怪，不知道怎么回事，早期用你的这个一点问题也没有，最近好久没用了。一用就不行。另外专项答题好像是有问题。我刚在注册表里面，把那个版本号手动改掉了。能完成每日答题，还有每周答题了。但是到专项的时候就出现如下错误了。抓取答案完成
答题:   0%|                                    | 0/10 [00:00<?, ?题/s]Traceback (most recent call last):
  File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\main.py", line 33, in <module>
    task.Task()
  File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Manage.py", line 214, in Task
    self.__Check_Project_Answer()
  File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Manage.py", line 192, in __Check_Project_Answer
    temp.Do(link=API().Project_Answer_Topic.geturl().format(num=iid))
  File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Answer.py", line 178, in Do
    self.__Do()
  File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Answer.py", line 156, in __Do
    topic_submit.click()
AttributeError: 'NoneType' object has no attribute 'click'

另外，每日答题和每周答题之间，会有一段时间没有反应，我还以为是坏了呢。
PS。现在答题的速度是真的快啊。上面还写的是干扰，我还以为有问题了呢

**Comment by lisztomania-Zero** [comment]
> 所以啊。特别的奇怪，不知道怎么回事，早期用你的这个一点问题也没有，最近好久没用了。一用就不行。另外专项答题好像是有问题。我刚在注册表里面，把那个版本号手动改掉了。能完成每日答题，还有每周答题了。但是到专项的时候就出现如下错误了。抓取答案完成
> 答题: 0%| | 0/10 [00:00<?, ?题/s]Traceback (most recent call last):
> File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\main.py", line 33, in
> task.Task()
> File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Manage.py", line 214, in Task
> self.__Check_Project_Answer()
> File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Manage.py", line 192, in __Check_Project_Answer
> temp.Do(link=API().Project_Answer_Topic.geturl().format(num=iid))
> File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Answer.py", line 178, in Do
> self.__Do()
> File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Answer.py", line 156, in __Do
> topic_submit.click()
> AttributeError: 'NoneType' object has no attribute 'click'
> 
> 另外，每日答题和每周答题之间，会有一段时间没有反应，我还以为是坏了呢。
> PS。现在答题的速度是真的快啊。上面还写的是干扰，我还以为有问题了呢

你这个报错是因为提交按钮没加载到，你重试就好了

**Comment by nqianaaron** [comment]
又运行了一次，还是一样的结果。。尴尬

**Comment by lisztomania-Zero** [comment]
> > 所以啊。特别的奇怪，不知道怎么回事，早期用你的这个一点问题也没有，最近好久没用了。一用就不行。另外专项答题好像是有问题。我刚在注册表里面，把那个版本号手动改掉了。能完成每日答题，还有每周答题了。但是到专项的时候就出现如下错误了。抓取答案完成
> > 答题: 0%| | 0/10 [00:00<?, ?题/s]Traceback (most recent call last):
> > File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\main.py", line 33, in
> > task.Task()
> > File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Manage.py", line 214, in Task
> > self.__Check_Project_Answer()
> > File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Manage.py", line 192, in __Check_Project_Answer
> > temp.Do(link=API().Project_Answer_Topic.geturl().format(num=iid))
> > File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Answer.py", line 178, in Do
> > self.__Do()
> > File "C:\Users\18621\Desktop\learning-power-master\learning-power-master\inside\Task\Task_Answer.py", line 156, in __Do
> > topic_submit.click()
> > AttributeError: 'NoneType' object has no attribute 'click'
> > 另外，每日答题和每周答题之间，会有一段时间没有反应，我还以为是坏了呢。
> > PS。现在答题的速度是真的快啊。上面还写的是干扰，我还以为有问题了呢
> 
> 你这个报错是因为提交按钮没加载到，你重试就好了



> 又运行了一次，还是一样的结果。。尴尬

网络没问题吧？报错之后，浏览器截图发一下

**Comment by nqianaaron** [comment]
网络没问题啊，千M电信网，富强就不说了。github我秒开，youtube也是；。浏览器没有任何反应，我又尝试了两次，同样结果。

**Comment by nqianaaron** [comment]
我淦，我换了台笔记本尝试，居然没问题了。浏览器都是一个版本的啊。同网络环境。

**Comment by lisztomania-Zero** [comment]
> 我淦，我换了台笔记本尝试，居然没问题了。浏览器都是一个版本的啊。同网络环境。
计算机是门玄学2333,
加载问题，这个我也没法控制，我想想办法吧。

**Comment by nqianaaron** [comment]
真的是一门玄学，另外吐槽一下，我github上下的另外一个脚本，反而我台式机能跑，笔记本就是报错。真心跪了。

**Comment by nqianaaron** [comment]
好像还有一个玄学，重启电脑就好了，我去试试，等会见。

**Comment by lisztomania-Zero** [comment]
> 真的是一门玄学，另外吐槽一下，我github上下的另外一个脚本，反而我台式机能跑，笔记本就是报错。真心跪了。



> 好像还有一个玄学，重启电脑就好了，我去试试，等会见。

行，我也想想办法吧

**Comment by nqianaaron** [comment]
不行，失敗了。然后我在vps上面也去尝试了下，也是win10的系统，也失败了。算了。先不折腾了。有一台笔记本能用就行了。期待大佬找到问题。

**Comment by e790a8** [comment]
> 不行，失敗了。然后我在vps上面也去尝试了下，也是win10的系统，也失败了。算了。先不折腾了。有一台笔记本能用就行了。期待大佬找到问题。

这个问题解决了，是因为缓存问题
