### ISSUE TITLE
每日答题测试有bug

### ISSUE THREAD

**Issue by yinshangwei** [lisztomania-Zero/learning-power#3]
环境：MacOS
选择每日答题，一直循环答题，分数没有增加。

**Comment by lisztomania-Zero** [comment]
暂时没有做异常处理，你重新启动试一下

**Comment by lisztomania-Zero** [comment]
> 环境：MacOS
> 选择每日答题，一直循环答题，分数没有增加。

我没有MacOs环境，进行测试

**Comment by yinshangwei** [comment]
原因知道了，是一个bug，当我的每日答题积分不是0分的时候，比如4分，我还差1分，跑每日答题，就只会去答第一道题，**但是每日答题必须要答完5道题才能提交成功**，所以程序会不断的轮询，不断的答题（只答第一道题）。

【修改点】将`task_manage.py` 第86行：
```
user_msg.USER_DAILY_ANSWER_TASKS = self.__user_tasks_number[
    self.__task_id[6]
]
```
改为
```
user_msg.USER_DAILY_ANSWER_TASKS = 5
```

**Comment by lisztomania-Zero** [comment]
> 原因知道了，是一个bug，当我的每日答题积分不是0分的时候，比如4分，我还差1分，跑每日答题，就只会去答第一道题，**但是每日答题必须要答完5道题才能提交成功**，所以程序会不断的轮询，不断的答题（只答第一道题）。
> 
> 【修改点】将`task_manage.py` 第86行：
> 
> ```
> user_msg.USER_DAILY_ANSWER_TASKS = self.__user_tasks_number[
>     self.__task_id[6]
> ]
> ```
> 
> 改为
> 
> ```
> user_msg.USER_DAILY_ANSWER_TASKS = 5
> ```

okok，这里设置成动态的了

**Comment by lisztomania-Zero** [comment]
> > 原因知道了，是一个bug，当我的每日答题积分不是0分的时候，比如4分，我还差1分，跑每日答题，就只会去答第一道题，**但是每日答题必须要答完5道题才能提交成功**，所以程序会不断的轮询，不断的答题（只答第一道题）。
> > 【修改点】将`task_manage.py` 第86行：
> > ```
> > user_msg.USER_DAILY_ANSWER_TASKS = self.__user_tasks_number[
> >     self.__task_id[6]
> > ]
> > ```
> > 
> > 
> > 改为
> > ```
> > user_msg.USER_DAILY_ANSWER_TASKS = 5
> > ```
> 
> okok，这里设置成动态的了

那专项答题应该也有这个bug，我改下
