### ISSUE TITLE
控制台pip的时候一直失败是什么情况？

### ISSUE THREAD

**Issue by mxeplan** [lisztomania-Zero/learning-power#32]
**pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
然后就出现如下信息**

Could not fetch URL https://mirrors.aliyun.com/pypi/simple/mitmproxy/: There was
 a problem confirming the ssl certificate: HTTPSConnectionPool(host='mirrors.ali
yun.com', port=443): Max retries exceeded with url: /pypi/simple/mitmproxy/ (Cau
sed by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] ce
rtificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))
) - skipping
ERROR: Could not find a version that satisfies the requirement mitmproxy~=6.0.2
(from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for mitmproxy~=6.0.2 (from -r requirements
.txt (line 1))
Could not fetch URL https://mirrors.aliyun.com/pypi/simple/pip/: There was a pro
blem confirming the ssl certificate: HTTPSConnectionPool(host='mirrors.aliyun.co
m', port=443): Max retries exceeded with url: /pypi/simple/pip/ (Caused by SSLEr
ror(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed: unable to get local issuer certificate (_ssl.c:1124)'))) - skipping

**请教大佬，是版本问题吗？**

**Comment by lisztomania-Zero** [comment]
> **pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple 然后就出现如下信息**
> 
> Could not fetch URL https://mirrors.aliyun.com/pypi/simple/mitmproxy/: There was
> a problem confirming the ssl certificate: HTTPSConnectionPool(host='mirrors.ali
> yun.com', port=443): Max retries exceeded with url: /pypi/simple/mitmproxy/ (Cau
> sed by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] ce
> rtificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))
> ) - skipping
> ERROR: Could not find a version that satisfies the requirement mitmproxy~=6.0.2
> (from -r requirements.txt (line 1)) (from versions: none)
> ERROR: No matching distribution found for mitmproxy~=6.0.2 (from -r requirements
> .txt (line 1))
> Could not fetch URL https://mirrors.aliyun.com/pypi/simple/pip/: There was a pro
> blem confirming the ssl certificate: HTTPSConnectionPool(host='mirrors.aliyun.co
> m', port=443): Max retries exceeded with url: /pypi/simple/pip/ (Caused by SSLEr
> ror(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
> rify failed: unable to get local issuer certificate (_ssl.c:1124)'))) - skipping
> 
> **请教大佬，是版本问题吗？**

pip的ssl问题，你更新一下pip就行了，百度一下有解决方案
