### ISSUE TITLE
WinError_10061_目标计算机积极拒绝_无法连接

### ISSUE THREAD

**Issue by magitwit** [lisztomania-Zero/learning-power#34]
作者你好，1.0新版出现这个bug。无论持久化登录 设置Y或者N 都会这样。
   过几天会自己修复正常登录 然后又一直这个提示，无法正常使用。
   旧版（重构之前的031)，会看到类似提示，但闪一下就能弹出二维码扫描登录。
   
现在只能继续使用旧版了，麻烦修复。感谢

![WinError_10061_目标计算机积极拒绝_无法连接](https://user-images.githubusercontent.com/78532402/106867753-f0115880-6708-11eb-93b1-316d366b426a.png)

**Comment by lisztomania-Zero** [comment]
> 作者你好，1.0新版出现这个bug。无论持久化登录 设置Y或者N 都会这样。
> 过几天会自己修复正常登录 然后又一直这个提示，无法正常使用。
> 旧版（重构之前的031)，会看到类似提示，但闪一下就能弹出二维码扫描登录。
> 
> 现在只能继续使用旧版了，麻烦修复。感谢
> 
> ![WinError_10061_目标计算机积极拒绝_无法连接](https://user-images.githubusercontent.com/78532402/106867753-f0115880-6708-11eb-93b1-316d366b426a.png)

你的网络正常吗？这是连接不上token存活检测api的报错

**Comment by magitwit** [comment]
> > 作者你好，1.0新版出现这个bug。无论持久化登录 设置Y或者N 都会这样。
> > 过几天会自己修复正常登录 然后又一直这个提示，无法正常使用。
> > 旧版（重构之前的031)，会看到类似提示，但闪一下就能弹出二维码扫描登录。
> > 现在只能继续使用旧版了，麻烦修复。感谢
> > ![WinError_10061_目标计算机积极拒绝_无法连接](https://user-images.githubusercontent.com/78532402/106867753-f0115880-6708-11eb-93b1-316d366b426a.png)
> 
> 你的网络正常吗？这是连接不上token存活检测api的报错

谢谢回复！网络一切正常的，1.0出错的 同一时间换回0.31版，能看到类似错误闪过，然后就弹出二维码扫描。
  所以现在还是只能用0.31旧版用

**Comment by lisztomania-Zero** [comment]
> > > 作者你好，1.0新版出现这个bug。无论持久化登录 设置Y或者N 都会这样。
> > > 过几天会自己修复正常登录 然后又一直这个提示，无法正常使用。
> > > 旧版（重构之前的031)，会看到类似提示，但闪一下就能弹出二维码扫描登录。
> > > 现在只能继续使用旧版了，麻烦修复。感谢
> > > ![WinError_10061_目标计算机积极拒绝_无法连接](https://user-images.githubusercontent.com/78532402/106867753-f0115880-6708-11eb-93b1-316d366b426a.png)
> > 
> > 
> > 你的网络正常吗？这是连接不上token存活检测api的报错
> 
> 谢谢回复！网络一切正常的，1.0出错的 同一时间换回0.31版，能看到类似错误闪过，然后就弹出二维码扫描。
> 所以现在还是只能用0.31旧版用

重试也是这样吗？

**Comment by magitwit** [comment]
> > 
> > 
> > 谢谢回复！网络一切正常的，1.0出错的 同一时间换回0.31版，能看到类似错误闪过，然后就弹出二维码扫描。
> > 所以现在还是只能用0.31旧版用
> 
> 重试也是这样吗？

是的，关闭软件，重启电脑也还是这样。但一般过几天或者第二天 就会自动好了
  同一时间031闪过类似错误然后就可以弹二维码扫描登录

**Comment by lisztomania-Zero** [comment]
> > > 谢谢回复！网络一切正常的，1.0出错的 同一时间换回0.31版，能看到类似错误闪过，然后就弹出二维码扫描。
> > > 所以现在还是只能用0.31旧版用
> > 
> > 
> > 重试也是这样吗？
> 
> 是的，关闭软件，重启电脑也还是这样。但一般过几天或者第二天 就会自动好了
> 同一时间031闪过类似错误然后就可以弹二维码扫描登录

你重新下载试一下

**Comment by magitwit** [comment]
> > > 
> > > 重试也是这样吗？
> > 
> > 
> > 是的，关闭软件，重启电脑也还是这样。但一般过几天或者第二天 就会自动好了
> > 同一时间031闪过类似错误然后就可以弹二维码扫描登录
> 
> 你重新下载试一下

最新版2.5号正常了一天，6号再开又是10061提示了，积极拒绝

**Comment by magitwit** [comment]
刚刚试了一下同一时间的031版本
  顺序是 弹出二维码，扫码，扫描后出错闪过类似积极拒绝 reconnect，然后正常进入功能界面

1.0最新版则是，跳出上面的截图，然后无法弹出二维码

**Comment by lisztomania-Zero** [comment]
> 弹出

你应该是运行成功过，也就是登录过，才会检测token的
报错信息最后的说明是check这个api连接不上，不过按道理你能访问xuexi.cn那么也能对它的其他链接进行访问；
而你也成功使用过，也就是说这种现象是间歇性的连接不上，这就和你的网络有很大的关系了。
可能你的网络很好，但是可能对于xuexi.cn不是太好。
以上是我的推测

**Comment by magitwit** [comment]
> 你应该是运行成功过，也就是登录过，才会检测token的
> 报错信息最后的说明是check这个api连接不上，不过按道理你能访问xuexi.cn那么也能对它的其他链接进行访问；
> 而你也成功使用过，也就是说这种现象是间歇性的连接不上，这就和你的网络有很大的关系了。
> 可能你的网络很好，但是可能对于xuexi.cn不是太好。
> 以上是我的推测

感谢作者回复！
我重新下新版这次观察了下，我设置不维持 但任务完成后没关cmd。过段时间自动出错
   然后 再打开软件就这样出错了。031的机制没这个问题，能不能修改成 如果选择不维持登陆 回归031这个验证机制？

**Comment by lisztomania-Zero** [comment]
> 如果选择不维持

嗯，目前就你反馈了这个问题，大家的应该没有问题
之所以换了验证机制，是因为加了无图模式和持久化登录，并且之前的验证机制，就是简单的检测url是否跳转
新的验证机制中先会去数据库查询token是否存在，如果存在则需要验证token是否有效，而你就是这一步连接验证的api出了问题；如果不存在则需要进行扫描登录，其中加入了检测二维码状态的api，而如果登录成功，这个api只会返回一次成功信息，过后的请求就是过期信息；
而加入无图模式后，二维码加载很快，就是当二维码加载出来了，你立马扫码登录了，此时浏览器的network中起码要等30秒左右的时间才会去向服务器请求二维码的状态，这就会白白等待30秒
所以我的措施是，以network为主、requests为副，当network中没有获取到二维码状态检测请求的时候，就会使用requests去查询二维码的状态，这样你立马扫码之后，就能快速的验证二维码的状态，从而直接跳转，而不需要等待30秒；如果你没有立马扫码，那么一旦检测到network中有状态请求了，就以network为主，再也不会调用requests了；
而且其中涉及到二维码过期的问题，而二维码过期的状态一定是从network中获取的，不会从requests获取；当过期了，需要涉及刷新二维码等操作。
所以总的来说，新的验证机制是为了持久化登录和提高速度才搞的这么细致的，而细致的东西，其中某个环节出了问题就可能gg；
旧的验证机制就比较粗暴，但是速度嘛，就慢了些。
而你出的问题，不是二维码验证机制的问题，而是token验证api连接的问题。

**Comment by magitwit** [comment]
> 所以总的来说，新的验证机制是为了持久化登录和提高速度才搞的这么细致的，而细致的东西，其中某个环节出了问题就可能gg；
> 旧的验证机制就比较粗暴，但是速度嘛，就慢了些。
> 而你出的问题，不是二维码验证机制的问题，而是token验证api连接的问题。

明白了…这个问题有没有好的临时解决办法？

**Comment by lisztomania-Zero** [comment]
> > 所以总的来说，新的验证机制是为了持久化登录和提高速度才搞的这么细致的，而细致的东西，其中某个环节出了问题就可能gg；
> > 旧的验证机制就比较粗暴，但是速度嘛，就慢了些。
> > 而你出的问题，不是二维码验证机制的问题，而是token验证api连接的问题。
> 
> 明白了…这个问题有没有好的临时解决办法？

你把sqlite数据库中user表清空
然后不要选持久化

**Comment by magitwit** [comment]
> 你把sqlite数据库中user表清空
> 然后不要选持久化

奇怪 就是选非持久化出现的问题。我试试 删除db文件？

**Comment by lisztomania-Zero** [comment]
> > 你把sqlite数据库中user表清空
> > 然后不要选持久化
> 
> 奇怪 就是选非持久化出现的问题。我试试 删除db文件？

因为user存在token，所以才会去验证token，没有token就不会去验证了

**Comment by magitwit** [comment]
> > > 你把sqlite数据库中user表清空
> > > 然后不要选持久化
> > 
> > 
> > 奇怪 就是选非持久化出现的问题。我试试 删除db文件？
> 
> 因为user存在token，所以才会去验证token，没有token就不会去验证了
删除db直接正常了 正好作者在 再反馈个问题。二次打开就会这样，需要删除drive目录等自动重新下载。麻烦检查修复一下。
   大于96的drive找不到下载 chrome自动更新了
![D285A454-095D-41C9-80A0-3855DF15631A](https://user-images.githubusercontent.com/78532402/107107853-b2c6db00-686e-11eb-82a5-f692821e7124.png)

**Comment by lisztomania-Zero** [comment]
> > > > 你把sqlite数据库中user表清空
> > > > 然后不要选持久化
> > > 
> > > 
> > > 奇怪 就是选非持久化出现的问题。我试试 删除db文件？
> > 
> > 
> > 因为user存在token，所以才会去验证token，没有token就不会去验证了
> > 删除db直接正常了 正好作者在 再反馈个问题。二次打开就会这样，需要删除drive目录等自动重新下载。麻烦检查修复一下。
> > 大于96的drive找不到下载 chrome自动更新了
> > ![D285A454-095D-41C9-80A0-3855DF15631A](https://user-images.githubusercontent.com/78532402/107107853-b2c6db00-686e-11eb-82a5-f692821e7124.png)

![image](https://user-images.githubusercontent.com/50130180/107108116-a3489180-6870-11eb-8493-3cc6ae424b0e.png)
![image](https://user-images.githubusercontent.com/50130180/107108141-d428c680-6870-11eb-812e-a5e522ddd4c0.png)
![image](https://user-images.githubusercontent.com/50130180/107108120-a774af00-6870-11eb-91f1-7d9aa8d37033.png)
![image](https://user-images.githubusercontent.com/50130180/107108129-b52a3480-6870-11eb-9898-25d882f9db74.png)
自动下载驱动是匹配版本号前三位，第四位为最大的那个驱动，目前驱动官网和你匹配的最大的就只有96
我的可以用啊！

**Comment by lisztomania-Zero** [comment]
> > > > > 你把sqlite数据库中user表清空
> > > > > 然后不要选持久化
> > > > 
> > > > 
> > > > 奇怪 就是选非持久化出现的问题。我试试 删除db文件？
> > > 
> > > 
> > > 因为user存在token，所以才会去验证token，没有token就不会去验证了
> > > 删除db直接正常了 正好作者在 再反馈个问题。二次打开就会这样，需要删除drive目录等自动重新下载。麻烦检查修复一下。
> > > 大于96的drive找不到下载 chrome自动更新了
> > > ![D285A454-095D-41C9-80A0-3855DF15631A](https://user-images.githubusercontent.com/78532402/107107853-b2c6db00-686e-11eb-82a5-f692821e7124.png)
> 
> ![image](https://user-images.githubusercontent.com/50130180/107108116-a3489180-6870-11eb-8493-3cc6ae424b0e.png)
> ![image](https://user-images.githubusercontent.com/50130180/107108141-d428c680-6870-11eb-812e-a5e522ddd4c0.png)
> ![image](https://user-images.githubusercontent.com/50130180/107108120-a774af00-6870-11eb-91f1-7d9aa8d37033.png)
> ![image](https://user-images.githubusercontent.com/50130180/107108129-b52a3480-6870-11eb-9898-25d882f9db74.png)
> 自动下载驱动是匹配版本号前三位，第四位为最大的那个驱动，目前驱动官网和你匹配的最大的就只有96
> 我的可以用啊！

因为驱动的问题，这我也没辙，我搞不出大于96版本的驱动

**Comment by magitwit** [comment]
> > 自动下载驱动是匹配版本号前三位，第四位为最大的那个驱动，目前驱动官网和你匹配的最大的就只有96
> > 我的可以用啊！
> 
> 因为驱动的问题，这我也没辙，我搞不出大于96版本的驱动

我知道的 是能用，但第二次打开就会提示上图错误。需要删掉drive让它再自动下载一次96
  如此反复

**Comment by lisztomania-Zero** [comment]
> 它

![image](https://user-images.githubusercontent.com/50130180/107108387-77c6a680-6872-11eb-8e62-8647e4d95354.png)
这个是代理的问题，之前有人遇到过，你把项目放到其他盘运行，别放C盘试试
他说他解决了

**Comment by magitwit** [comment]
> > 它
> 
> ![image](https://user-images.githubusercontent.com/50130180/107108387-77c6a680-6872-11eb-8e62-8647e4d95354.png)
> 这个是代理的问题，之前有人遇到过，你把项目放到其他盘运行，别放C盘试试
> 他说他解决了

换了 没解决。等驱动版本跟上就好了

**Comment by lisztomania-Zero** [comment]
> > > 它
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/50130180/107108387-77c6a680-6872-11eb-8e62-8647e4d95354.png)
> > 这个是代理的问题，之前有人遇到过，你把项目放到其他盘运行，别放C盘试试
> > 他说他解决了
> 
> 换了 没解决。等驱动版本跟上就好了

问题是我这边可以啊，所以不是驱动的问题啊，你看下8080端口，或者任务管理器中有什么任务导致代理出错

**Comment by magitwit** [comment]
两个问题基本上能解决，Closed。期待继续优化更新

**Comment by magitwit** [comment]
两个问题基本上能解决，Closed。期待继续优化更新
