### ISSUE TITLE
填空题多个需要填写时程序出现问题

### ISSUE THREAD

**Issue by HungKin** [lisztomania-Zero/learning-power#35]
2018年10月第四周答题，题目二为两个填空，程序只填写了一个就提交，导致找不到确定按钮。
![答题页](https://user-images.githubusercontent.com/26057519/106916569-3d88c800-66ff-11eb-8d9f-3b2a4d70cf74.png)
![代码页](https://user-images.githubusercontent.com/26057519/106916609-48435d00-66ff-11eb-9c3c-642ca9d8fa1d.png)

**Comment by lisztomania-Zero** [comment]
> 2018年10月第四周答题，题目二为两个填空，程序只填写了一个就提交，导致找不到确定按钮。
> ![答题页](https://user-images.githubusercontent.com/26057519/106916569-3d88c800-66ff-11eb-8d9f-3b2a4d70cf74.png)
> ![代码页](https://user-images.githubusercontent.com/26057519/106916609-48435d00-66ff-11eb-9c3c-642ca9d8fa1d.png)

已修复

**Comment by lisztomania-Zero** [comment]
感谢反馈
