### ISSUE TITLE
选择文章，打开后为视频

### ISSUE THREAD

**Issue by Lin1031** [lisztomania-Zero/learning-power#36]
全选之后，文章的分数一直不增加。单独测试之后发现，选择文章实际为视频。

![xuexi1](https://user-images.githubusercontent.com/44975556/107064722-d4947380-6816-11eb-9eb8-c40d9461be36.jpg)
![xuexi2](https://user-images.githubusercontent.com/44975556/107064875-060d3f00-6817-11eb-844b-cedaaef5cce4.png)
![xuexi3](https://user-images.githubusercontent.com/44975556/107064885-09082f80-6817-11eb-8941-ea88fee0cc6a.jpg)

**Comment by lisztomania-Zero** [comment]
> 全选之后，文章的分数一直不增加。单独测试之后发现，选择文章实际为视频。
> 
> ![xuexi1](https://user-images.githubusercontent.com/44975556/107064722-d4947380-6816-11eb-9eb8-c40d9461be36.jpg)
> ![xuexi2](https://user-images.githubusercontent.com/44975556/107064875-060d3f00-6817-11eb-844b-cedaaef5cce4.png)
> ![xuexi3](https://user-images.githubusercontent.com/44975556/107064885-09082f80-6817-11eb-8941-ea88fee0cc6a.jpg)

啊？不应该啊，我这是通过服务器传过来的类型进行判断的，难道它标的是tuwen类型，其实是shipin类型？
我再看看，有什么能代替这个方式。
现阶段建议，把sqlite数据库中video表清空后运行

**Comment by Lin1031** [comment]
> > 全选之后，文章的分数一直不增加。单独测试之后发现，选择文章实际为视频。
> > ![xuexi1](https://user-images.githubusercontent.com/44975556/107064722-d4947380-6816-11eb-9eb8-c40d9461be36.jpg)
> > ![xuexi2](https://user-images.githubusercontent.com/44975556/107064875-060d3f00-6817-11eb-844b-cedaaef5cce4.png)
> > ![xuexi3](https://user-images.githubusercontent.com/44975556/107064885-09082f80-6817-11eb-8941-ea88fee0cc6a.jpg)
> 
> 啊？不应该啊，我这是通过服务器传过来的类型进行判断的，难道它标的是tuwen类型，其实是shipin类型？
> 我再看看，有什么能代替这个方式。
> 现阶段建议，把sqlite数据库中video表清空后运行

我也很奇怪，然后我今天发现昨天帮舍友配置的这个程序，他的文章可以用，我都就bug了。我把数据库清空试试。

**Comment by Lin1031** [comment]
数据库清空，正常。应该只是一个bug。
