### ISSUE TITLE
mitmproxy 下载不了

### ISSUE THREAD

**Issue by NoAIGhost** [lisztomania-Zero/learning-power#37]
C:\1>pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement mitmproxy~=6.0.2
ERROR: No matching distribution found for mitmproxy~=6.0.2

**Comment by lisztomania-Zero** [comment]
> C:\1>pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
> Looking in indexes: https://mirrors.aliyun.com/pypi/simple
> ERROR: Could not find a version that satisfies the requirement mitmproxy~=6.0.2
> ERROR: No matching distribution found for mitmproxy~=6.0.2

呃，这个我就不清楚了，我能装上
