### ISSUE TITLE
切换账号的话？

### ISSUE THREAD

**Issue by nie-e** [lisztomania-Zero/learning-power#38]
同事有两三个左右，但是设置自动登录的话，打开默认就自动登录了， 咋切换账号= =。
我尝试在开一个命令，也不行，也无法一个刷完后，在重新登录一个

**Comment by lisztomania-Zero** [comment]
> 同事有两三个左右，但是设置自动登录的话，打开默认就自动登录了， 咋切换账号= =。
> 我尝试在开一个命令，也不行，也无法一个刷完后，在重新登录一个

你把项目复制几份就可以了。

**Comment by nie-e** [comment]
原来如此，谢谢大佬！  新版这个我试了一下，驱动下载报错了，也不知道啥情况、emmm ，还是旧版好点，还是谢谢大佬啦
