### ISSUE TITLE
大佬请问这个错误是什么原因呀

### ISSUE THREAD

**Issue by Dairce** [lisztomania-Zero/learning-power#39]
D:\learning-power-master>python main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from inside.Driver.Driver_Manage import DRIVER_MANAGE
  File "D:\learning-power-master\inside\Driver\Driver_Manage.py", line 11, in <module>
    from selenium.webdriver.chrome.webdriver import WebDriver
ModuleNotFoundError: No module named 'selenium'

**Comment by lisztomania-Zero** [comment]
> D:\learning-power-master>python main.py
> Traceback (most recent call last):
> File "main.py", line 12, in
> from inside.Driver.Driver_Manage import DRIVER_MANAGE
> File "D:\learning-power-master\inside\Driver\Driver_Manage.py", line 11, in
> from selenium.webdriver.chrome.webdriver import WebDriver
> ModuleNotFoundError: No module named 'selenium'

把依赖安装一下

**Comment by Dairce** [comment]
> > D：\ learning-power-master> python main.py
> > 回溯（最近一次调用最后一次）：
> > 文件“ main.py”，第12行，
> > 从内部开始。Driver.Driver_Manage导入DRIVER_MANAGE
> > 文件“ D：\ learning-power-master” \ inside \ Driver \ Driver_Manage.py“，第11行，
> > 来自selenium.webdriver.chrome.webdriver导入WebDriver 
> > ModuleNotFoundError：没有名为“ selenium”的模块
> 
> 把依赖安装一下

安装了的

**Comment by lisztomania-Zero** [comment]
> > > D：\ learning-power-master> python main.py
> > > 回溯（最近一次调用最后一次）：
> > > 文件“ main.py”，第12行，
> > > 从内部开始。Driver.Driver_Manage导入DRIVER_MANAGE
> > > 文件“ D：\ learning-power-master” \ inside \ Driver \ Driver_Manage.py“，第11行，
> > > 来自selenium.webdriver.chrome.webdriver导入WebDriver
> > > ModuleNotFoundError：没有名为“ selenium”的模块
> > 
> > 
> > 把依赖安装一下
> 
> 安装了的

你没装selenium依赖

**Comment by Dairce** [comment]
> > > > D：\ learning-power-master> python main.py
> > > > 回溯（最近一次调用最后一次）：
> > > > 文件“ main.py”，第12行，
> > > > 从内部开始。Driver.Driver_Manage导入DRIVER_MANAGE
> > > > 文件“ D：\ learning-power-master” \ inside \ Driver \ Driver_Manage.py“，第11行，
> > > > 来自selenium.webdriver.chrome.webdriver导入WebDriver
> > > > ModuleNotFoundError：没有名为“ selenium”的模块
> > > 
> > > 
> > > 把依赖安装一下
> > 
> > 
> > 安装了的
> 
> 你没装selenium依赖

D:\learning-power-master>python main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from inside.Options.Options_Manage import OPTIONS_MANAGE
  File "D:\learning-power-master\inside\Options\Options_Manage.py", line 10, in <module>
    from inside.Baidu_AI.Baidu_AI_Manage import BAIDU_AI_MANAGE
  File "D:\learning-power-master\inside\Baidu_AI\Baidu_AI_Manage.py", line 10, in <module>
    from inside.Baidu_AI.Baidu_AI_Tools import BAIDU_AI_TOOLS
  File "D:\learning-power-master\inside\Baidu_AI\Baidu_AI_Tools.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by Dairce** [comment]
> > > > D：\ learning-power-master> python main.py
> > > > 回溯（最近一次调用最后一次）：
> > > > 文件“ main.py”，第12行，
> > > > 从内部开始。Driver.Driver_Manage导入DRIVER_MANAGE
> > > > 文件“ D：\ learning-power-master” \ inside \ Driver \ Driver_Manage.py“，第11行，
> > > > 来自selenium.webdriver.chrome.webdriver导入WebDriver
> > > > ModuleNotFoundError：没有名为“ selenium”的模块
> > > 
> > > 
> > > 把依赖安装一下
> > 
> > 
> > 安装了的
> 
> 你没装selenium依赖

D:\learning-power-master>python main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from inside.Options.Options_Manage import OPTIONS_MANAGE
  File "D:\learning-power-master\inside\Options\Options_Manage.py", line 10, in <module>
    from inside.Baidu_AI.Baidu_AI_Manage import BAIDU_AI_MANAGE
  File "D:\learning-power-master\inside\Baidu_AI\Baidu_AI_Manage.py", line 10, in <module>
    from inside.Baidu_AI.Baidu_AI_Tools import BAIDU_AI_TOOLS
  File "D:\learning-power-master\inside\Baidu_AI\Baidu_AI_Tools.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
然后这样了 大佬

**Comment by lisztomania-Zero** [comment]
> > > > > D：\ learning-power-master> python main.py
> > > > > 回溯（最近一次调用最后一次）：
> > > > > 文件“ main.py”，第12行，
> > > > > 从内部开始。Driver.Driver_Manage导入DRIVER_MANAGE
> > > > > 文件“ D：\ learning-power-master” \ inside \ Driver \ Driver_Manage.py“，第11行，
> > > > > 来自selenium.webdriver.chrome.webdriver导入WebDriver
> > > > > ModuleNotFoundError：没有名为“ selenium”的模块
> > > > 
> > > > 
> > > > 把依赖安装一下
> > > 
> > > 
> > > 安装了的
> > 
> > 
> > 你没装selenium依赖
> 
> D:\learning-power-master>python main.py
> Traceback (most recent call last):
> File "main.py", line 14, in
> from inside.Options.Options_Manage import OPTIONS_MANAGE
> File "D:\learning-power-master\inside\Options\Options_Manage.py", line 10, in
> from inside.Baidu_AI.Baidu_AI_Manage import BAIDU_AI_MANAGE
> File "D:\learning-power-master\inside\Baidu_AI\Baidu_AI_Manage.py", line 10, in
> from inside.Baidu_AI.Baidu_AI_Tools import BAIDU_AI_TOOLS
> File "D:\learning-power-master\inside\Baidu_AI\Baidu_AI_Tools.py", line 11, in
> import cv2
> ModuleNotFoundError: No module named 'cv2'
> 然后这样了 大佬

opencv-python没装

**Comment by lisztomania-Zero** [comment]
> > > > > > D：\ learning-power-master> python main.py
> > > > > > 回溯（最近一次调用最后一次）：
> > > > > > 文件“ main.py”，第12行，
> > > > > > 从内部开始。Driver.Driver_Manage导入DRIVER_MANAGE
> > > > > > 文件“ D：\ learning-power-master” \ inside \ Driver \ Driver_Manage.py“，第11行，
> > > > > > 来自selenium.webdriver.chrome.webdriver导入WebDriver
> > > > > > ModuleNotFoundError：没有名为“ selenium”的模块
> > > > > 
> > > > > 
> > > > > 把依赖安装一下
> > > > 
> > > > 
> > > > 安装了的
> > > 
> > > 
> > > 你没装selenium依赖
> > 
> > 
> > D:\learning-power-master>python main.py
> > Traceback (most recent call last):
> > File "main.py", line 14, in
> > from inside.Options.Options_Manage import OPTIONS_MANAGE
> > File "D:\learning-power-master\inside\Options\Options_Manage.py", line 10, in
> > from inside.Baidu_AI.Baidu_AI_Manage import BAIDU_AI_MANAGE
> > File "D:\learning-power-master\inside\Baidu_AI\Baidu_AI_Manage.py", line 10, in
> > from inside.Baidu_AI.Baidu_AI_Tools import BAIDU_AI_TOOLS
> > File "D:\learning-power-master\inside\Baidu_AI\Baidu_AI_Tools.py", line 11, in
> > import cv2
> > ModuleNotFoundError: No module named 'cv2'
> > 然后这样了 大佬
> 
> opencv-python没装

你把依赖装好行不？
