### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by legolas-zeng** [lisztomania-Zero/learning-power#40]
![image](https://user-images.githubusercontent.com/27952739/107182495-d11c0a80-6a17-11eb-928e-c3eab29507ee.png)

```
是否静音(Y/n):y
是否显示自动化过程(y/N):y
是否持久化登录(Y/n):b
是否使用百度AI(y/N):y
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    MITMDUMP().Open()
  File "F:\下载\learning-power-1.1\inside\Task\Mitmdump\Mitmdump.py", line 37, in Open
    ['mitmdump', '-q', '-p', '8080', '-s', PATH().Script]
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```
请问下，这个问题是怎么回事？我用的是win10的，python3.7

**Comment by yxnwh** [comment]
持久化登录那里，要么y，要么n，你输个b。。。

**Comment by legolas-zeng** [comment]
![image](https://user-images.githubusercontent.com/27952739/107188793-4214ef80-6a23-11eb-8921-10299cc85be9.png)

**Comment by legolas-zeng** [comment]
是否静音(Y/n):y
是否显示自动化过程(y/N):y
是否持久化登录(Y/n):y
是否使用百度AI(y/N):y
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    MITMDUMP().Open()
  File "F:\下载\learning-power-1.1\inside\Task\Mitmdump\Mitmdump.py", line 37, in Open
    ['mitmdump', '-q', '-p', '8080', '-s', PATH().Script]
  File "C:\Python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

F:\下载\learning-power-1.1>

**Comment by legolas-zeng** [comment]
改了还是报这个错误

**Comment by legolas-zeng** [comment]
改了还是报这个错误

**Comment by e790a8** [comment]
不应该啊，你是否有这个文件？inside/Task/Mitmdump/Intercept/Script.py

**Comment by legolas-zeng** [comment]
有的
![image](https://user-images.githubusercontent.com/27952739/107237293-89ba6c00-6a61-11eb-862d-b1ed2a25c5ff.png)

**Comment by e790a8** [comment]
> 有的
> ![image](https://user-images.githubusercontent.com/27952739/107237293-89ba6c00-6a61-11eb-862d-b1ed2a25c5ff.png)

你用重新下载试试

**Comment by ilovecode2018** [comment]
这应该是系统安装了多个python版本，然后没有找到mitmdump.exe路径的问题。我是把绝对路径写到mitmdump.py文件来解决的。

**Comment by legolas-zeng** [comment]
> 绝对路径

**Comment by legolas-zeng** [comment]
> 这应该是系统安装了多个python版本，然后没有找到mitmdump.exe路径的问题。我是把绝对路径写到mitmdump.py文件来解决的。

请问绝对路径在哪里修改

**Comment by WeichenGu** [comment]
> > 这应该是系统安装了多个python版本，然后没有找到mitmdump.exe路径的问题。我是把绝对路径写到mitmdump.py文件来解决的。
> 
> 请问绝对路径在哪里修改

同问各位大佬，不知道咋改
