### ISSUE TITLE
大佬我的运行不成功

### ISSUE THREAD

**Issue by lcqadmin** [lisztomania-Zero/learning-power#43]
![S34`}85VCRJ3KG0XXA~SW S](https://user-images.githubusercontent.com/74635842/107604805-2a7c7780-6c6c-11eb-9bce-0238cbcfe2a5.png)
这是怎么回事？

**Comment by freshn** [comment]
conda install selenium

**Comment by e790a8** [comment]
> ![S34`}85VCRJ3KG0XXA~SW S](https://user-images.githubusercontent.com/74635842/107604805-2a7c7780-6c6c-11eb-9bce-0238cbcfe2a5.png)
> 这是怎么回事？

依赖没装
