### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by iHinx** [lisztomania-Zero/learning-power#45]
![image](https://user-images.githubusercontent.com/64398676/107777166-7539e480-6d7d-11eb-9603-e38b86cd2a39.png)

**Comment by iHinx** [comment]
新年好!
系统:Windows Server 2012
环境依赖已安装

**Comment by e790a8** [comment]
> 新年好!
> 系统:Windows Server 2012
> 环境依赖已安装

这个是opencv-python没装

**Comment by iHinx** [comment]
![image](https://user-images.githubusercontent.com/64398676/107876471-261cbc80-6f01-11eb-9238-35b592cf6e2f.png)

**Comment by e790a8** [comment]
你并没有安装成功，并且你的pip该升级了

**Comment by iHinx** [comment]
谢谢大佬耐心的解答，不过我还是没弄好，算了 放弃了
