### ISSUE TITLE
输入完百度api就无法运行了

### ISSUE THREAD

**Issue by donqee** [lisztomania-Zero/learning-power#46]
是否静音(Y/n):y
是否显示自动化过程(y/N):y
是否持久化登录(Y/n):y
是否使用百度AI(y/N):y
Traceback (most recent call last):
  File "D:\xuexi\learning-power-1.1\main.py", line 24, in <module>
    MITMDUMP().Open()
  File "D:\xuexi\learning-power-1.1\inside\Task\Mitmdump\Mitmdump.py", line 36, in Open
    self.__mitmdump = subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

我是从win商店安装Python

**Comment by e790a8** [comment]
> 是否静音(Y/n):y
> 是否显示自动化过程(y/N):y
> 是否持久化登录(Y/n):y
> 是否使用百度AI(y/N):y
> Traceback (most recent call last):
> File "D:\xuexi\learning-power-1.1\main.py", line 24, in
> MITMDUMP().Open()
> File "D:\xuexi\learning-power-1.1\inside\Task\Mitmdump\Mitmdump.py", line 36, in Open
> self.__mitmdump = subprocess.Popen(
> File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
> hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> 
> 我是从win商店安装Python

根据你的报错信息，是在启动拦截脚本的时候，找不到拦截脚本文件而导致的报错
你可以把整个项目移至其他盘，或者重新下载最新的项目

**Comment by donqee** [comment]
> > 是否静音(Y/n):y
> > 是否显示自动化过程(y/N):y
> > 是否持久化登录(Y/n):y
> > 是否使用百度AI(y/N):y
> > Traceback (most recent call last):
> > File "D:\xuexi\learning-power-1.1\main.py", line 24, in
> > MITMDUMP().Open()
> > File "D:\xuexi\learning-power-1.1\inside\Task\Mitmdump\Mitmdump.py", line 36, in Open
> > self.__mitmdump = subprocess.Popen(
> > File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in **init**
> > self._execute_child(args, executable, preexec_fn, close_fds,
> > File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
> > hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> > FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> > 我是从win商店安装Python
> 
> 根据你的报错信息，是在启动拦截脚本的时候，找不到拦截脚本文件而导致的报错
> 你可以把整个项目移至其他盘，或者重新下载最新的项目

挪动了盘符，从新下载了文件，还是不行，还是同样的报错信息，难过。。。。。

**Comment by donqee** [comment]
已经解决了，从新安装了python就解决了，从windows商店安装的无法允许，我卸载了从新从官网下载离线安装包就可以完美允许。
