### ISSUE TITLE
Win10 Python 3.9.1环境下运行失败

### ISSUE THREAD

**Issue by DoveBoy** [lisztomania-Zero/learning-power#47]
![image](https://user-images.githubusercontent.com/19201447/108160589-4ed0cc00-7124-11eb-83c2-c464757971b7.png)
如图所示的，Python环境以及所需要的pip包都安装了，但是运行失败，求解

**Comment by e790a8** [comment]
> ![image](https://user-images.githubusercontent.com/19201447/108160589-4ed0cc00-7124-11eb-83c2-c464757971b7.png)
> 如图所示的，Python环境以及所需要的pip包都安装了，但是运行失败，求解

你的Chrome是默认安装的吗？还是有过迁移？

**Comment by DoveBoy** [comment]
@lisztomania-Zero 我的Chrome是绿色版的，非安装版，项目运行是需要自行下载安装版的Chrome？还是会自动下载Chrome到项目的目录下的？程序调用的Chrome是本机已安装的Chrome吗？

**Comment by e790a8** [comment]
> @lisztomania-Zero 我的Chrome是绿色版的，非安装版，项目运行是需要自行下载安装版的Chrome？还是会自动下载Chrome到项目的目录下的？程序调用的Chrome是本机已安装的Chrome吗？

呃，我这是默认Google官网的Chrome，因为会默认装到C盘，且ChromeDriver也是Google出的
不建议使用非官方的软件，很有可能存在病毒等其他安全问题。
项目会自动根据Chrome版本下载对应的ChromeDriver，并不会自动下载Chrome。

**Comment by DoveBoy** [comment]
@lisztomania-Zero 正是因为Google官网下载Chrome会默认安装到C盘会占用大量空间才选择绿色版的，除了换Chrome官方安装版，可有其他方式解决？

**Comment by DoveBoy** [comment]
![image](https://user-images.githubusercontent.com/19201447/108162124-6a89a180-7127-11eb-9e5e-f725eddace80.png)
@lisztomania-Zero 如果用这个安装Chrome能解决吗？

**Comment by e790a8** [comment]
> @lisztomania-Zero 正是因为Google官网下载Chrome会默认安装到C盘会占用大量空间才选择绿色版的，除了换Chrome官方安装版，可有其他方式解决？

你可以更改项目代码
在inside/Driver/Driver_Init.py的__init__中的__config['goog:chromeOptions']中添加
'binary':r'你的chrome.exe绝对路径'
如：'binary': 'D:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'

**Comment by DoveBoy** [comment]
@lisztomania-Zero `Driver_Init.py`中在35行后面`'goog:chromeOptions':`直接添加Chrome的绝对路径`'binary': 'D:\Program Files (x86)\Google\Chrome\Application\chrome.exe'`？
![image](https://user-images.githubusercontent.com/19201447/108189805-20ff7d80-714c-11eb-8cca-4df5a30206fa.png)

**Comment by e790a8** [comment]
> @lisztomania-Zero `Driver_Init.py`中在35行后面`'goog:chromeOptions':`直接添加Chrome的绝对路径`'binary': 'D:\Program Files (x86)\Google\Chrome\Application\chrome.exe'`？
> ![image](https://user-images.githubusercontent.com/19201447/108189805-20ff7d80-714c-11eb-8cca-4df5a30206fa.png)

。。。我裂开了
![image](https://user-images.githubusercontent.com/50130180/108203360-5eb8d200-715d-11eb-8bb9-8dddd348153b.png)

**Comment by e790a8** [comment]
> > @lisztomania-Zero `Driver_Init.py`中在35行后面`'goog:chromeOptions':`直接添加Chrome的绝对路径`'binary': 'D:\Program Files (x86)\Google\Chrome\Application\chrome.exe'`？
> > ![image](https://user-images.githubusercontent.com/19201447/108189805-20ff7d80-714c-11eb-8cca-4df5a30206fa.png)
> 
> 。。。我裂开了
> ![image](https://user-images.githubusercontent.com/50130180/108203360-5eb8d200-715d-11eb-8bb9-8dddd348153b.png)

你的IDE没有报错提示么？

**Comment by DoveBoy** [comment]
@lisztomania-Zero 我填了，没运行测试，我就觉得这么填很奇怪，所以确定一下

**Comment by DoveBoy** [comment]
@lisztomania-Zero 也许描述为`36`和`37`行之间插入`binary': 'D:\Program Files (x86)\Google\Chrome\Application\chrome.exe`更好理解一些吧，小白莫怪，哈哈

**Comment by DoveBoy** [comment]
@lisztomania-Zero 已按照说明自定义了Chrome安装位置，但是报新的错误了
![image](https://user-images.githubusercontent.com/19201447/108299890-42a74600-71da-11eb-89c9-64045de46834.png)
![image](https://user-images.githubusercontent.com/19201447/108299921-50f56200-71da-11eb-9234-5b6aa7aa86dd.png)

**Comment by e790a8** [comment]
> @lisztomania-Zero 已按照说明自定义了Chrome安装位置，但是报新的错误了
> ![image](https://user-images.githubusercontent.com/19201447/108299890-42a74600-71da-11eb-89c9-64045de46834.png)
> ![image](https://user-images.githubusercontent.com/19201447/108299921-50f56200-71da-11eb-9234-5b6aa7aa86dd.png)

还是那个文件，加上这些
![image](https://user-images.githubusercontent.com/50130180/108300210-e5f85b00-71da-11eb-8b19-4f23c4e1729c.png)
![image](https://user-images.githubusercontent.com/50130180/108300270-00323900-71db-11eb-91b9-feacc70472d6.png)

**Comment by e790a8** [comment]
> > @lisztomania-Zero 已按照说明自定义了Chrome安装位置，但是报新的错误了
> > ![image](https://user-images.githubusercontent.com/19201447/108299890-42a74600-71da-11eb-89c9-64045de46834.png)
> > ![image](https://user-images.githubusercontent.com/19201447/108299921-50f56200-71da-11eb-9234-5b6aa7aa86dd.png)
> 
> 还是那个文件，加上这些
> ![image](https://user-images.githubusercontent.com/50130180/108300210-e5f85b00-71da-11eb-8b19-4f23c4e1729c.png)
> ![image](https://user-images.githubusercontent.com/50130180/108300270-00323900-71db-11eb-91b9-feacc70472d6.png)

路径是你的Chrome.exe绝对路径，别忘了

**Comment by DoveBoy** [comment]
@lisztomania-Zero 还是报错
![image](https://user-images.githubusercontent.com/19201447/108442530-29fa6700-7292-11eb-8eb4-e088945e2dce.png)
![image](https://user-images.githubusercontent.com/19201447/108442656-5b733280-7292-11eb-9917-33acda9826e9.png)
![image](https://user-images.githubusercontent.com/19201447/108442593-45657200-7292-11eb-89ac-6562137d7d97.png)

**Comment by e790a8** [comment]
> @lisztomania-Zero 还是报错
> ![image](https://user-images.githubusercontent.com/19201447/108442530-29fa6700-7292-11eb-8eb4-e088945e2dce.png)
> ![image](https://user-images.githubusercontent.com/19201447/108442656-5b733280-7292-11eb-9917-33acda9826e9.png)
> ![image](https://user-images.githubusercontent.com/19201447/108442593-45657200-7292-11eb-89ac-6562137d7d97.png)

我炸了
你的,号呢？128行最后。

**Comment by DoveBoy** [comment]
@lisztomania-Zero 我也很奇怪，不知道为什么128行的`,`怎么就没了，现在可以了，谢谢
