### ISSUE TITLE
pip 出错 No matching distribution found for mitmproxy~=6.0.2

### ISSUE THREAD

**Issue by bao3** [lisztomania-Zero/learning-power#51]
按照 README 说明，无论是用 pip 默认源还是用阿里源，都会提示找不到 mitmproxy：
```

ERROR: Could not find a version that satisfies the requirement mitmproxy~=6.0.2
ERROR: No matching distribution found for mitmproxy~=6.0.2
```

但是实际上 mitmproxy 是有这个版本的 [](https://pypi.org/project/mitmproxy/#history) 。于是先尝试使用 `pip install mitmproxy ` 安装，结果安装的是 `/usr/local/lib/python3.7/dist-packages (5.3.0) `

我检查了自己的 pip 版本， ` pip --version ` ，得到的结果是 `pip 21.0.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7) `

看起来好像也没什么问题。。。。所以是哪里出错了。

> python3 -m pip install -r requirements.txt 结果也是一样的。

**Comment by e790a8** [comment]
> 按照 README 说明，无论是用 pip 默认源还是用阿里源，都会提示找不到 mitmproxy：
> 
> ```
> 
> ERROR: Could not find a version that satisfies the requirement mitmproxy~=6.0.2
> ERROR: No matching distribution found for mitmproxy~=6.0.2
> ```
> 
> 但是实际上 mitmproxy 是有这个版本的 。于是先尝试使用 `pip install mitmproxy ` 安装，结果安装的是 `/usr/local/lib/python3.7/dist-packages (5.3.0) `
> 
> 我检查了自己的 pip 版本， `pip --version` ，得到的结果是 `pip 21.0.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7) `
> 
> 看起来好像也没什么问题。。。。所以是哪里出错了。
> 
> > python3 -m pip install -r requirements.txt 结果也是一样的。

严格来说，你的问题不属于本脚本的解决范畴
而如果你去PyPI进行搜索了，你就会发现，6.0.2只支持Python3.8和3.9
![image](https://user-images.githubusercontent.com/50130180/108956859-64596f00-76ab-11eb-9ad5-9ce106f30fbe.png)

**Comment by bao3** [comment]
谢谢，学习到了，看来我还是不够细心。

我后来自己的解决办法是 git clone  了 mitmproxy 的源码，然后 python3.7 setup.py install 的。安装上之后是 7.0-dev，也可以用。

发自我的iPad
