### ISSUE TITLE
依赖 Chrome 是为什么？

### ISSUE THREAD

**Issue by bao3** [lisztomania-Zero/learning-power#52]
请问我是在 Linux 的服务器站运行，但是运行依赖 Chrome，依赖 Chrome 的原因是什么，就为了生成二维码吗？能不能做成 headless 的。

**Comment by e790a8** [comment]
> 请问我是在 Linux 的服务器站运行，但是运行依赖 Chrome，依赖 Chrome 的原因是什么，就为了生成二维码吗？能不能做成 headless 的。

依赖Chrome的原因：
1、用的是ChromeDriver，执行的自动化操作
为什么要用chrome生成二维码：
1、因为我也尝试在控制台直接输出二维码，输出的二维码会失真，就是会因为控制台的大小等问题，导致输出的二维码根本无法扫，所以我就将二维码输出至Chrome，以保证二维码能被扫
如果你有更好的方法，能在（windows、linux、macos）控制台输出不会失真的二维码，我马上替换二维码输出模块。
其实脚本的主体是默认headless的
