### ISSUE TITLE
系统找不到指定的文件

### ISSUE THREAD

**Issue by sparklerl** [lisztomania-Zero/learning-power#57]
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    MITMDUMP().Open()
  File "D:\github_project\learning-power-1.1\inside\Task\Mitmdump\Mitmdump.py", line 36, in Open
    self.__mitmdump = subprocess.Popen(
  File "C:\Program Files\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

这个缺啥？

**Comment by sparklerl** [comment]
pip 安装必需环境的时候有warn，要将安装的组件路径加入系统环境路径中，就不缺啥了

**Comment by hupo376787** [comment]
你好，安装warn后，是把他的路径加入到path环境变量吗，谢谢

**Comment by sparklerl** [comment]
在安装requirements的组件时，看看warn的信息，将对应的路径加入环境变量，我是这么解决的；
“_winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。”其实是找不到executable这个对应的可执行程序，这个如果不是全路径，那就需要文件所在路径在系统环境变量PATH里面了。

**Comment by hupo376787** [comment]
> 在安装requirements的组件时，看看warn的信息，将对应的路径加入环境变量，我是这么解决的；
> “_winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。”其实是找不到executable这个对应的可执行程序，这个如果不是全路径，那就需要文件所在路径在系统环境变量PATH里面了。

谢谢，我把python全部卸载了，因为有多个版本。重新安装就好了。
