### ISSUE TITLE
关于视频任务问题

### ISSUE THREAD

**Issue by kakusang2020** [lisztomania-Zero/learning-power#9]
你好，非常感谢你的软件。
我使用其他几个选项都正常工作。
但在尝试播放视频的时候失败了。
浏览器显示.json结尾的文件下载失败，请问您有什么建议吗？

**Comment by lisztomania-Zero** [comment]
修复了

**Comment by kakusang2020** [comment]
> 修复了

新版本扫码后显示：
Traceback (most recent call last):
  File "F:\...\learning-power-master (1)\learning-power-master\main.py", line 19, in <module>
    task_manage = Task_Manage(driver=driver)
  File "F:\...\learning-power-master (1)\learning-power-master\task\task_manage.py", line 50, in __init__
    self.__init_article_video_tasks()
  File "F:\...\learning-power-master (1)\learning-power-master\task\task_manage.py", line 122, in __init_article_video_tasks
    self.__analysis_task = Analysis_Task(task_driver=self.__driver)
TypeError: __init__() got an unexpected keyword argument 'task_driver'
无法进入

**Comment by yinshangwei** [comment]
一个bug，将`self.__analysis_task = Analysis_Task(task_driver=self.__driver)`改成`self.__analysis_task = Analysis_Task()`就行了

**Comment by lisztomania-Zero** [comment]
呃，忘记改这边了

**Comment by kakusang2020** [comment]
> 呃，忘记改这边了

感谢，现在正常工作了

**Comment by kakusang2020** [comment]
> 一个bug，将`self.__analysis_task = Analysis_Task(task_driver=self.__driver)`改成`self.__analysis_task = Analysis_Task()`就行了

感谢，现在正常工作了

**Comment by holodfall** [comment]
我出现的是这个问题：
选择(选项请使用空格隔开，退出输入0):2
视频任务不足，正在获取中:1
视频任务不足，正在获取中:2
视频任务不足，正在获取中:3
视频任务不足，正在获取中:4
视频任务不足，正在获取中:5
视频任务不足，正在获取中:6
视频任务不足，正在获取中:7

**Comment by kakusang2020** [comment]
> 我出现的是这个问题：
> 选择(选项请使用空格隔开，退出输入0):2
> 视频任务不足，正在获取中:1
> 视频任务不足，正在获取中:2
> 视频任务不足，正在获取中:3
> 视频任务不足，正在获取中:4
> 视频任务不足，正在获取中:5
> 视频任务不足，正在获取中:6
> 视频任务不足，正在获取中:7

我之前的日志显示也是这样，按照上面说的改了就没事了

**Comment by kakusang2020** [comment]
> 我出现的是这个问题：
> 选择(选项请使用空格隔开，退出输入0):2
> 视频任务不足，正在获取中:1
> 视频任务不足，正在获取中:2
> 视频任务不足，正在获取中:3
> 视频任务不足，正在获取中:4
> 视频任务不足，正在获取中:5
> 视频任务不足，正在获取中:6
> 视频任务不足，正在获取中:7

请问你现在这个问题解决了吗，我这边又出现找个问题了。。。

**Comment by e790a8** [comment]
> > 我出现的是这个问题：
> > 选择(选项请使用空格隔开，退出输入0):2
> > 视频任务不足，正在获取中:1
> > 视频任务不足，正在获取中:2
> > 视频任务不足，正在获取中:3
> > 视频任务不足，正在获取中:4
> > 视频任务不足，正在获取中:5
> > 视频任务不足，正在获取中:6
> > 视频任务不足，正在获取中:7
> 
> 请问你现在这个问题解决了吗，我这边又出现找个问题了。。。

这个是正常现象
